### ISSUE TITLE
一直显示页面无法用eval

### ISSUE THREAD

**Issue by pokefunc** [extend-luogu/extend-luogu#312]
rt,从大概半个月左右之前开始，每次想改badge都显示页面不可以用eval。
尝试过包括但并不限于换浏览器、卸掉油猴重装的办法无果。
浏览器：Chrome 102.0.5005.115（正式版本）（64 位），Edge 102.0.1245.33 (正式版本) (64 位)

**Comment by immccn123** [comment]
+1
浏览器：Microsoft Edge 102.0.1245.33
```
[exlg] 错误信息:  ReferenceError: colorFormat is not defined
    at eval (colorFormat.min.js:76:19)
    at ./src/colorFormat.min.js (eval at <anonymous> (www.luogu.com.cn/:136:19107), <anonymous>:10:82)
    at __webpack_require__ (eval at <anonymous> (www.luogu.com.cn/:136:19107), <anonymous>:46:433)
    at eval (xncolorpicker.js:27:23)
    at ./src/xncolorpicker.js (eval at <anonymous> (www.luogu.com.cn/:136:19107), <anonymous>:13:97)
    at __webpack_require__ (eval at <anonymous> (www.luogu.com.cn/:136:19107), <anonymous>:46:433)
    at eval (eval at <anonymous> (www.luogu.com.cn/:136:19107), <anonymous>:46:1091)
    at eval (eval at <anonymous> (www.luogu.com.cn/:136:19107), <anonymous>:46:1137)
    at eval (<anonymous>)
    at userscript.html?name=extend-luogu.user.js&id=2a78b47f-c7e6-4411-ab44-2492b4db9f65:136:19107
X @ userscript.html?name=extend-luogu.user.js&id=2a78b47f-c7e6-4411-ab44-2492b4db9f65:55
(匿名) @ userscript.html?name=extend-luogu.user.js&id=2a78b47f-c7e6-4411-ab44-2492b4db9f65:136
(匿名) @ userscript.html?name=extend-luogu.user.js&id=2a78b47f-c7e6-4411-ab44-2492b4db9f65:58
onclick @ userscript.html?name=extend-luogu.user.js&id=2a78b47f-c7e6-4411-ab44-2492b4db9f65:176
dispatch @ userscript.html?name=extend-luogu.user.js&id=2a78b47f-c7e6-4411-ab44-2492b4db9f65:4
r.handle @ userscript.html?name=extend-luogu.user.js&id=2a78b47f-c7e6-4411-ab44-2492b4db9f65:4
```

**Comment by juruo888** [comment]
~~他妈的测试版为啥他妈的不用啊~~

请使用 [最新测试版](https://github.com/extend-luogu/extend-luogu/blob/preview/dist/extend-luogu.min.user.js) 即可解决该问题
